export const ProductPreviewApi={
    cowork:[
        {
            id: "0",
            url: "cowork",
            ImgSrc: "cowork/preview/home-page1.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/home-page1.webp",
        },
        {
            id: "1",
            url: "cowork",
            ImgSrc: "cowork/preview/home-page2.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/home-page2.webp",
        },
        {
            id: "2",
            url: "cowork",
            ImgSrc: "cowork/preview/home-page4.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/home-page4.webp",
        },
        {
            id: "3",
            url: "cowork",
            ImgSrc: "cowork/preview/list-filter1.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list-filter1.webp",
        },
        {
            id: "4",
            url: "cowork",
            ImgSrc: "cowork/preview/list-filter2.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list-filter2.webp",
        },
        {
            id: "5",
            url: "cowork",
            ImgSrc: "cowork/preview/list1.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list1.webp",
        },
        {
            id: "6",
            url: "cowork",
            ImgSrc: "cowork/preview/list2.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list2.webp",
        },
        {
            id: "7",
            url: "cowork",
            ImgSrc: "cowork/preview/list3.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list3.webp",
        },
        {
            id: "8",
            url: "cowork",
            ImgSrc: "cowork/preview/list4.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list4.webp",
        },
        {
            id: "9",
            url: "cowork",
            ImgSrc: "cowork/preview/list5.png",
            ImgAlt: "Despription",
            WebpSrc: "cowork/preview/list5.webp",
        }
    ],
    skilify:[
        {
            id: "0",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img1.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img1.webp",
        },
        {
            id: "1",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img2.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img2.webp",
        },
        {
            id: "2",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img3.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img3.webp",
        },
        {
            id: "3",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img4.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img4.webp",
        },
        {
            id: "4",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img5.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img5.webp",
        },
        {
            id: "5",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img6.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img6.webp",
        },
        {
            id: "6",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img7.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img7.webp",
        },
        {
            id: "7",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img8.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img8.webp",
        },
        {
            id: "8",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img9.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img9.webp",
        },
        {
            id: "9",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img10.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img10.webp",
        },
        {
            id: "10",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img11.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img11.webp",
        },
        {
            id: "11",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img12.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img12.webp",
        },
        {
            id: "12",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img13.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img13.webp",
        },
        {
            id: "13",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img14.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img14.webp",
        },
        {
            id: "14",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img15.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img15.webp",
        },
        {
            id: "15",
            url: "skilify",
            ImgSrc: "skilify-education/preview/skilify-img16.jpg",
            ImgAlt: "Despription",
            WebpSrc: "skilify-education/preview/skilify-img16.webp",
        }
    ],
    barber:[
        {
            id: "0",
            url: "barber",
            ImgSrc: "barber-shop/preview/barber-img1.png",
            ImgAlt: "Despription",
            WebpSrc: "barber-shop/preview/barber-img1.webp",
        }
    ]
}